# -*- coding: utf-8 -*-
"""Linear_Road.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nsD86ZBcFVey8rqjg7kucGihi52NGyYN
"""

from google.colab import drive
drive.mount("/content/gdrive")

!pip install ultralytics

import os
from ultralytics import YOLO
from google.colab import drive

drive.mount("/content/gdrive", force_remount=True)

ROOT_DIR = "/content/gdrive/My Drive/linear_roads"

model = YOLO('yolov8n-seg.pt')
results = model.train(data=os.path.join(ROOT_DIR, r"data.yaml"), epochs=20)

val_results = model.val(data=os.path.join(ROOT_DIR, "data.yaml"))

test_results = model.val(data=os.path.join(ROOT_DIR, "data.yaml"), task='test')